// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCxbxke0lpyuqZgcl9kMRJsuHfa0kKRTiU',
    appId: '1:1050448420383:web:37ddb6035e6fcd6b82ff2a',
    messagingSenderId: '1050448420383',
    projectId: 'laravelflutter-e7baf',
    authDomain: 'laravelflutter-e7baf.firebaseapp.com',
    storageBucket: 'laravelflutter-e7baf.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBqbNPNYdJqBaUqB7m3m31WvrjtuPVIBOk',
    appId: '1:1050448420383:android:fa39ae9b826afc4a82ff2a',
    messagingSenderId: '1050448420383',
    projectId: 'laravelflutter-e7baf',
    storageBucket: 'laravelflutter-e7baf.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCKjcOnHHNTklAs0kqAjGq7Y7W0EhV-Ucc',
    appId: '1:1050448420383:ios:b8e31e0088f10c8582ff2a',
    messagingSenderId: '1050448420383',
    projectId: 'laravelflutter-e7baf',
    storageBucket: 'laravelflutter-e7baf.appspot.com',
    iosClientId: '1050448420383-4j1ieiuj0b50gchljnv21k7vkv3bds33.apps.googleusercontent.com',
    iosBundleId: 'com.example.laravelFlutter',
  );
}
